name: FFmpeg Job

on:
  workflow_dispatch:
    inputs:
      ffmpeg_command:
        description: 'FFmpeg command to execute'
        required: true

jobs:
  ffmpeg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up FFmpeg
        run: |
          sudo add-apt-repository ppa:ubuntuhandbook1/ffmpeg7 -y > /dev/null
          sudo apt update -y -qq > /dev/null
          sudo apt install ffmpeg -y -qq > /dev/null
      - name: Run FFmpeg
        run: |
          while true; do
            ${{ github.event.inputs.ffmpeg_command }}
            if [ $? -ne 0 ]; then
              echo "FFmpeg stopped with error code $?. Restarting..."
              sleep 5
            fi
          done
